pavancoin/miner/urls.py
from django.urls import path
from miner.views import *
urlpatterns = [
    path('',mine),
    path('show_blockchain/',show_blockchain),
]

pavancoin/pavancoin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallet/', include('wallet.urls')),
    path('mine_api/', include('miner.urls')),
]

pavancoin/wallet/urls.py
from django.urls import path
from wallet.views import *

app_name='wallet'

urlpatterns = [
    path('new_wallet/', new_wallet,name='new_wallet'),
    path('new_wallet_form/', new_wallet_form,name='new_wallet_form'),
    path('make_transaction/',make_transaction,name='make_transaction'),
    path('check_balance/', check_balance,name='check_balance'),
]

pavancoin/miner/models.py
from django.db import models

# Create your models here.

pavancoin/wallet/models.py
from django.db import models

# Create your models here.

pavancoin/miner/views.py
import requests
from miner.utils import *
import pickle
from django.http import HttpResponse

# Create your views here.
def mine(request):
    blockchain = requests.get('http://localhost:8000/mine_api/show_blockchain')
    miner_public_key=request.GET['pkey']
    if(len(blockchain.text)==0):
        save_blockchain([create_genesis_block()])

    transaction=pickle.load('./pavancoin/unverified_transactions.dat')

    validate_signature(transaction['front'],transaction['signature'],transaction['message'])

    last_block = blockchain[len(blockchain) - 1]
    last_proof = last_block.data['proof-of-work']
    proof = proof_of_work(last_proof,blockchain)

    # Empty transaction list
    NODE_PENDING_TRANSACTIONS = []

    NODE_PENDING_TRANSACTIONS.append({
        "from": "network",
        "to": miner_public_key,
        "amount": 5})

    new_block_data = {
        "proof-of-work": proof[0],
        "transactions": list(NODE_PENDING_TRANSACTIONS)
    }
    new_block_index = last_block.index + 1
    new_block_timestamp = time.time()
    last_block_hash = last_block.hash

    # Now create the new block
    mined_block = Block(new_block_index, new_block_timestamp, new_block_data, last_block_hash)
    blockchain.append(mined_block)
    with open("./pavancoin/blockchain.dat",'wb') as df:
        df.write(blockchain)
    df.close()

    return HttpResponse(str(blockchain))


def show_blockchain(request):
    blockchain=pickle.load("blockchain.dat")
    return HttpResponse(str(blockchain))

pavancoin/wallet/views.py
from django.http import HttpResponse
import json
from wallet.utils import *
import requests
import pickle
from django.shortcuts import render

# Create your views here.
def new_wallet_form(request):
    return render(request,'wallet/index.html',{})

def new_wallet(request):
    sk = ecdsa.SigningKey.generate(curve=ecdsa.SECP256k1)
    private_key = sk.to_string().hex()
    vk = sk.get_verifying_key()
    public_key = vk.to_string().hex()
    public_key = base64.b64encode(bytes.fromhex(public_key))
    context = {'private_key': private_key, 'public_key': public_key}
    return HttpResponse(str(context))


def make_transaction(request):
    sender_public_key=request.POST["sender_public"]
    sender_private_key=request.POST["sender_private"]
    reciever_public_key=request.POST["reciever_public"]
    amount=request.POST["amount"]
    if len(sender_private_key == 64):
        signature,message=sign_ECDSA_msg(sender_private_key)

        unverified_transaction = {"from": sender_public_key,
                   "to": reciever_public_key,
                   "amount": amount,
                   "signature": signature.decode(),
                   "message": message}

        pickle.dump('unverified_transactions.dat',unverified_transaction)

    return HttpResponse(str(unverified_transaction))


def check_balance(request):
    public_key=request.POST['public_key']
    blockchain=requests.get('http://localhost:8000/mine_api/show_blockchain')
    balance=0
    for block in blockchain:
        if (block.data['transactions']['sender'] )== public_key:
            balance-=block.data['transactions']['amount']
        else:
            balance += block.data['transactions']['amount']
    context={'balance':balance}
    return HttpResponse(str(context))

pavancoin/wallet/templates/wallet/front.html
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
@import url('https://fonts.googleapis.com/css?family=Roboto');

body{
  font-family: 'Roboto', sans-serif;
}

h2{
  margin:0px;
  text-transform: uppercase;
}

h6{
  margin:0px;
  color:#777;
}

.wrapper{
  text-align:center;
  margin:50px auto;
}

.tabs{
  margin-top:50px;
  font-size:15px;
  padding:0px;
  list-style:none;
  background:#fff;
  box-shadow:0px 5px 20px rgba(0,0,0,0.1);
  display:inline-block;
  border-radius:50px;
  position:relative;
}

.tabs a{
  text-decoration:none;
  color: #777;
  text-transform:uppercase;
  padding:10px 20px;
  display:inline-block;
  position:relative;
  z-index:1;
  transition-duration:0.6s;
}

.tabs a.active{
  color:#fff;
}

.tabs a i{
  margin-right:5px;
}

.tabs .selector{
  height:100%;
  display:inline-block;
  position:absolute;
  left:0px;
  top:0px;
  z-index:1;
  border-radius:50px;
  transition-duration:0.6s;
  transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);
  background: #05abe0;

}

</style>
</head>
<body>
<div class="wrapper">
  <h2>Elastic Tabs</h2>
  <h6>Click on tabs to see them in action</h6>
  <nav class="tabs">
    <div class="selector"></div>
    <a href="#" class="active"><i class="fab fa-superpowers"></i>Avengers</a>
    <a href="#"><i class="fas fa-hand-rock"></i>Hulk</a>
    <a href="#"><i class="fas fa-bolt"></i>Thor</a>
    <a href="#"><i class="fas fa-burn"></i>Marvel</a>
  </nav>
</div>
<script >
	var tabs = $('.tabs');
var selector = $('.tabs').find('a').length;
//var selector = $(".tabs").find(".selector");
var activeItem = tabs.find('.active');
var activeWidth = activeItem.innerWidth();
$(".selector").css({
  "left": activeItem.position.left + "px", 
  "width": activeWidth + "px"
});

$(".tabs").on("click","a",function(e){
  e.preventDefault();
  $('.tabs a').removeClass("active");
  $(this).addClass('active');
  var activeWidth = $(this).innerWidth();
  var itemPos = $(this).position();
  $(".selector").css({
    "left":itemPos.left + "px", 
    "width": activeWidth + "px"
  });
});

</script>
</body>

</html>

pavancoin/wallet/templates/wallet/index.html
<html>
<head>
  <style type="text/css">

    @import url('https://fonts.googleapis.com/css?family=Work+Sans:400,600');
body {
  margin: 0;
  background: #222;
  font-family: 'Work Sans', sans-serif;
  font-weight: 800;
}

.container {
  width: 80%;
  margin: 0 auto;
}

header {
  background: #55d6aa;
}

header::after {
  content: '';
  display: table;
  clear: both;
}

.logo {
  float: left;
  padding: 8px 0;
  font-size: 20px;
  text-decoration: none;
  margin-left: -50px;
}

nav {
  float: right;
}

nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav li {
  display: inline-block;
  margin-left: 70px;
  padding-top: 23px;

  position: relative;
}

nav a {
  color: #444;
  text-decoration: none;
  text-transform: uppercase;
  font-size: 14px;
}

nav a:hover {
  color: #000;
}

nav a::before {
  content: '';
  display: block;
  height: 5px;
  background-color: #444;

  position: absolute;
  top: 0;
  width: 0%;

  transition: all ease-in-out 250ms;
}

nav a:hover::before {
  width: 100%;
}

.name{

  margin-top: 2px;
  padding:0px ;
  text-decoration: none;


}







.login-box{
  width: 500px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  color: white;
}
.login-box h1{
  float: left;
  font-size: 40px;
  border-bottom: 6px solid #4caf50;
  margin-bottom: 50px;
  padding: 13px 0;
}
.textbox{
  width: 100%;
  overflow: hidden;
  font-size: 20px;
  padding: 8px 0;
  margin: 8px 0;
  border-bottom: 1px solid #4caf50;
}
.textbox i{
  width: 26px;
  float: left;
  text-align: center;
}
.textbox input{
  border: none;
  outline: none;
  background: none;
  color: white;
  font-size: 18px;
  width: 80%;
  float: left;
  margin: 0 10px;
}
.btn{
  width: 100%;
  background: none;
  border: 2px solid #4caf50;
  color: white;
  padding: 5px;
  font-size: 18px;
  cursor: pointer;
  margin: 12px 0;
}

  </style>
</head><header>
    <div class="container">
      <h1 class="logo"></h1>
      <h1><span class="logo">SVVVCOIN</span><h1>
      <nav>
        <ul>
          <li><a href="#">Create Wallet</a></li>
          <li><a href="transaction.html">Create transaction</a></li>
          <li><a href="#">Check Balance</a></li>

        </ul>
      </nav>
    </div>
  </header>
  <div class="login-box">
  <h1>Generate Key</h1>
  <div class="textbox">
    <i class="fas fa-user"></i>
    <input type="text" placeholder="Private Key" id="private">
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="password" placeholder="Public Key" id="public">
  </div>

  <input type="button" class="btn" id="btn1" value="Generate">
</div>

<!--Ajax part-->
<script type="text/javascript">
	var btn=document.getElementById("btn1");
	btn.addEventListener("click",function(){
			var url="{% url 'wallet:new_wallet' %}"
            var public=document.getElementById("public")
            var private=document.getElementById("private")
			//console.log(url)
			var req=new XMLHttpRequest();
			req.open('GET',url)
			req.onload=function()
            {
				var data=JSON.parse(req.responseText);
				console.log(data.public_key);
				public.innerText=data.public_key;
                private.innerHTML=data.private_key;
			};
			req.send();
	});
</script>

</html>

pavancoin/wallet/templates/wallet/make_transaction.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blockchain Client</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<link href="custom.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav >
      <div class="container">
        <a class="navbar-brand" href="#">Blockchain Client</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Wallet Generator
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/make/transaction">Make Transaction</a>
              <span class="sr-only">(current)</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/view/transactions">View Transactions</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <div class="row">
        <div class="col-lg-12">

          <div class="card-body">
            <h4 class="card-title">Send Coins</h4>
            <p class="card-text">Enter transaction details and click on "Generate Transaction" button to generate your transaction</p>
          </div>

        </div>
      </div>
    </div>

    <br>


    <div class="container alert alert-secondary">
    <form id="transaction_form">

        <div class="row">
          <label class="col-sm-2">Sender Address:</label>
          <div class="col-sm-10">
            <input type="text" name="sender_address" id="sender_address" rows="2" class="form-control">

          </div>
        </div>

        <br>
        
        <div class="row">
          <label class="col-sm-2">Sender Private Key:</label>
          <div class="col-sm-10">
            <input type="text" name="sender_private_key" id="sender_private_key" rows="2" class="form-control">
          </div>
        </div>

        <br>
        
        <div class="row">
          <label class="col-sm-2">Recipient Address:</label>
          <div class="col-sm-10">
            <input type="text" name="recipient_address" id="recipient_address" rows="2" class="form-control">
          </div>
        </div>

        <br>
        
        <div class="row">
          <label class="col-sm-2">Amount to Send:</label>
          <div class="col-sm-10">
            <input type="text" name="amount" id="amount" rows="2" class="form-control">
          </div>
        </div>

        <br>
        
        <div class="row">
          <div class="col-lg-12 text-center">
            <input type="button" id="generate_transaction" class="btn btn-primary btn-lg" value="Generate Transaction">
          </div>
        </div>

        <br>

    </form>
    </div>


    <!-- Modal -->
    <div class="modal modal-alert fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
      <div class="modal-dialog">

        <div class="modal-content">

          <div class="modal-header">
            <div class="modal-title col-md-10">Confirm transaction details, enter a blockchain node url and click on "Confirm Transaction" to finalize your transaction.</div>
            <button type="button" class="close col-md-2" data-dismiss="modal" aria-hidden="true">&times;</button>
          </div>

          <div class="modal-body">

            <form id="confirmation_transaction_form">

                <div class="row">
                  <label class="col-sm-12">Sender Address:</label>
                  <div class="col-sm-12">
                    <input type="text" name="sender_address" id="confirmation_sender_address" rows="2" class="form-control" readonly>

                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-12">Recipient Address:</label>
                  <div class="col-sm-12">
                    <input type="text" name="recipient_address" id="confirmation_recipient_address" rows="2" class="form-control" readonly>
                  </div>
                </div>
                
                <div class="row">
                  <label class="col-sm-12">Amount to Send:</label>
                  <div class="col-sm-12">
                    <input type="text" name="amount" id="confirmation_amount" rows="2" class="form-control" readonly>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-12">Transaction Signature:</label>
                  <div class="col-sm-12">
                    <input type="text" name="signature" id="transaction_signature" rows="2" class="form-control" readonly>
                  </div>
                </div>

            </form>


            <div class="row">
              <label class="col-sm-12">Blockchain Node URL:</label>
              <div class="col-sm-12">
                <input type="text" name="node_url" id="node_url" rows="2" class="form-control" value="http://127.0.0.1:5000">
              </div>
            </div>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <button type="button" id="button_confirm_transaction" class="btn btn-success">Confirm Transaction</button>
          </div>

        </div>

      </div>
    </div>


    <!-- Alert Message for successful transaction -->
    <div class="modal modal-alert fade" id="success_transaction_modal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          </div>

          <div class="modal-body">
            <div class="alert alert-success" role="alert">
              <h4 class="alert-heading">Successful Transaction!</h4>
              <p>You successfully completed your transaction. It will be added to the next block.</p>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" id="button_confirm_transaction" class="btn btn-success" data-dismiss="modal">OK</button>
          </div>

        </div>
      </div>
    </div>



    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <script>

      $(function () {
          $("#generate_transaction").click(function () {

            $.ajax({
              url: "/generate/transaction",
              type: "POST",
              dataType : 'json',
              data: $('#transaction_form').serialize(),
              success: function(response){

                document.getElementById("confirmation_sender_address").value = response["transaction"]["sender_address"];
                document.getElementById("confirmation_recipient_address").value = response["transaction"]["recipient_address"];
                document.getElementById("confirmation_amount").value = response["transaction"]["value"];
                document.getElementById("transaction_signature").value = response["signature"];

                $("#basicModal").modal('show');
                
              },
              error: function(error){
                console.log(error);
              }
            });

          });
      });


      $(function () {
          $("#button_confirm_transaction").click(function () {
            //console.log($('#confirmation_transaction_form').serialize());


            $.ajax({
              url: document.getElementById("node_url").value + "/transactions/new",
              type: "POST",
              headers: {'Access-Control-Allow-Origin':'*'},
              dataType : 'json',
              data: $('#confirmation_transaction_form').serialize(),
              success: function(response){

                //reset both forms
                $("#transaction_form")[0].reset();
                $("#confirmation_transaction_form")[0].reset();
                
                //clean text boxes
                $("#sender_address").val("");
                $("#sender_private_key").val("");
                $("#recipient_address").val("");
                $("#amount").val("");

                $("#basicModal").modal('hide');
                $("#success_transaction_modal").modal('show');
                
              },
              error: function(error){
                console.log(error);
              }
            });

          });
      });

    </script>


  </body>

</html>

pavancoin/wallet/templates/wallet/transaction.html
<head>
  <style type="text/css">
  	@import url('https://fonts.googleapis.com/css?family=Work+Sans:400,600');
body {
	margin: 0;
	background: #222;
	font-family: 'Work Sans', sans-serif;
	font-weight: 800;
}

.container {
	width: 80%;
	margin: 0 auto;
}

header {
  background: #55d6aa;
}

header::after {
  content: '';
  display: table;
  clear: both;
}

.logo {
  float: left;
  padding: 8px 0;
  font-size: 20px;
  text-decoration: none;
  margin-left: -50px;
}

nav {
  float: right;
}

nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav li {
  display: inline-block;
  margin-left: 70px;
  padding-top: 23px;

  position: relative;
}

nav a {
  color: #444;
  text-decoration: none;
  text-transform: uppercase;
  font-size: 14px;
}

nav a:hover {
  color: #000;
}

nav a::before {
  content: '';
  display: block;
  height: 5px;
  background-color: #444;

  position: absolute;
  top: 0;
  width: 0%;

  transition: all ease-in-out 250ms;
}

nav a:hover::before {
  width: 100%;
}

.name{

  margin-top: 2px;
  padding:0px ;
  text-decoration: none;


}







.login-box{
  width: 500px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  color: white;
}
.login-box h1{
  float: left;
  font-size: 40px;
  border-bottom: 6px solid #4caf50;
  margin-bottom: 50px;
  padding: 13px 0;
}
.textbox{
  width: 100%;
  overflow: hidden;
  font-size: 20px;
  padding: 8px 0;
  margin: 8px 0;
  border-bottom: 1px solid #4caf50;
}
.textbox i{
  width: 26px;
  float: left;
  text-align: center;
}
.textbox input{
  border: none;
  outline: none;
  background: none;
  color: white;
  font-size: 18px;
  width: 80%;
  float: left;
  margin: 0 10px;
}
.btn{
  width: 100%;
  background: none;
  border: 2px solid #4caf50;
  color: white;
  padding: 5px;
  font-size: 18px;
  cursor: pointer;
  margin: 12px 0;
}

  </style>
</head><header>
    <div class="container">
      <h1 class="logo"></h1>
      <h1><span class="logo">SVVVCOIN</span><h1>
      <nav>
        <ul>
          <li><a href="index1.html">Create Wallet</a></li>
          <li><a href="less/transaction.html">Create transaction</a></li>
          <li><a href="#">Check Balance</a></li>
          
        </ul>
      </nav>
    </div>
  </header>
  <div class="login-box">
  <h1>Make Transaction</h1>
  <div class="textbox">
    <i class="fas fa-user"></i>
    <input type="text" placeholder="Private Key Sender">
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="password" placeholder="Public Key Sender">
  </div>
  <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="password" placeholder="Public Key Reciver">
  </div>
  <div class="textbox">
    <i class="fas fa-lock"></i>
    <input type="password" placeholder="Amount">
  </div>

  <input type="button" class="btn" value="Generate">
</div>

pavancoin/wallet/templates/wallet/view_transactions.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blockchain Client</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/DataTables/css/datatables.min.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Blockchain Client</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Wallet Generator
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/make/transaction">Make Transaction</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/view/transactions">View Transactions
                <span class="sr-only">(current)</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <!-- Blockchain Node URL Selector -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">

          <div class="card-body">
            <h4 class="card-title">View Transactions</h4>
            <p class="card-text">Enter a blockchain node URL and click on "View Transactions" button to check all transactions</p>
          </div>

        </div>
      </div>
    </div>

    <div class="container alert alert-secondary">

        <div class="row">
          <label class="col-sm-2">Node URL:</label>
          <div class="col-sm-10">
            <textarea id="node_url" rows="1" class="form-control">http://127.0.0.1:5000</textarea>
          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-lg-12 text-center">
            <input type="button" id="view_transactions" class="btn btn-primary btn-lg" value="View Transactions">
          </div>
        </div>

    </div>

    <br>
    <!-- Blockchain Transactions Table -->
    <div class="container">
      <table id="transactions_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
      </table>
    </div>


    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="/static/vendor/DataTables/js/datatables.min.js"></script>
    <script src="/static/vendor/DataTables/js/ellipsis.js"></script>


    <script>

      $(function(){

        
        $('#view_transactions').click(function(){

          $.ajax({
            url: document.getElementById("node_url").value + "/chain",
            type: 'GET',
            success: function(response){

              console.log(response);
              //Generate Transactions Table
              var transactions = [];
              count = 1;

              for (i = 1; i < response.length; i++) { 
                for (j = 0; j < response["chain"][i]["transactions"].length; j++) {

                  //format date 
                  var options = {  year: "numeric", month: "short",  day: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit"  };
                  var date = new Date(response["chain"][i]["timestamp"] * 1000);
                  var formattedDateTime = date.toLocaleTimeString("en-us", options);

                  transaction = [count,
                                response["chain"][i]["transactions"][j]["recipient_address"],
                                response["chain"][i]["transactions"][j]["sender_address"],
                                response["chain"][i]["transactions"][j]["value"],
                                formattedDateTime,
                                response["chain"][i]["block_number"]];
                  transactions.push(transaction);

                  count += 1;
                };
              };

              // Restrict a column to 10 characters, do split words
                $('#transactions_table').dataTable( {
                  data: transactions,
                  columns: [{ title: "#" },
                            { title: "Recipient Address"},
                            { title: "Sender Address"},
                            { title: "Value"},
                            { title: "Timestamp"},
                            { title: "Block"}],
                  columnDefs: [ {targets: [1,2,3,4,5], render: $.fn.dataTable.render.ellipsis( 25 )}]
                } );

            },
            error: function(error){
              console.log(error);
            }
          });
        });


      })




    </script>



  </body>

</html>